export const configKeys = {
  HTTP_SERVER_PORT: 'HTTP_SERVER_PORT',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION: 'JWT_EXPIRATION',

  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
  REDIS_DB: 'REDIS_DB',
  REDIS_EX: 'REDIS_EX',

  HEADER_USER_ID: 'HEADER_USER_ID',
  HEADER_IS_ADMIN: 'HEADER_IS_ADMIN',

  SMTP_HOST: 'SMTP_HOST',
  SMTP_USERNAME: 'SMTP_USERNAME',
  SMTP_PASSWORD: 'SMTP_PASSWORD',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_SECURE: 'SMTP_SECURE',
  SMTP_FROM: 'SMTP_FROM',

  APP_URL: 'APP_URL',
};
